name: auto-Assign Reviewer and Assignee

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ vars.REVIEWERS }}
